- link:
    ~/.ssh/config:
      path: ssh/config
      create: true
    ~/.hammerspoon:
    ~/.skhdrc: yabai/skhdrc
    ~/.yabairc: yabai/yabairc

- shell:
  - [/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)", Installing Homebrew]
  - [pyenv install 3.8.5, Installing Python 3.8.5]
  - [cd /usr/local/bin && ln -s gcc-10 gcc && cd, Creating gcc symlink]
  - [touch ~/.hushlogin, Hushing login in terminal]
