- clean: ['~']

- link:
    ~/.zshrc:
    ~/.vim:
    ~/.vimrc:
    ~/.tmux.conf:

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh, Installing Oh My Zsh]
  - [git clone https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k, Installing powerlevel10k] 
  - [git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm, Installing TPM]
